disable parsing tables due to an error, and enable debug print
Error:
        18: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNote.rb:173:in `new'
        17: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:46:in `initialize'
        16: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:203:in `rebuild_table'
        15: from /home/l/gems/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:193:in `execute'
        14: from /home/l/gems/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:151:in `prepare'
        13: from /home/l/gems/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:198:in `block in execute'
        12: from /home/l/gems/gems/sqlite3-1.4.2/lib/sqlite3/resultset.rb:134:in `each'
        11: from /home/l/gems/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:199:in `block (2 levels) in execute'
        10: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:248:in `block in rebuild_table'
         9: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:248:in `each'
         8: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:250:in `block (2 levels) in rebuild_table'
         7: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:158:in `parse_table'
         6: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:158:in `each'
         5: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:173:in `block in parse_table'
         4: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:131:in `parse_cell_columns'
         3: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:131:in `each'
         2: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:136:in `block in parse_cell_columns'
         1: from /home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:136:in `each'
/home/l/notes-test/apple_cloud_notes_parser/lib/AppleNotesEmbeddedTable.rb:142:in `block (2 levels) in parse_cell_columns': undefined method `[]=' for nil:NilClass (NoMethodError)

Afterwards, notes can be dumped, excluding tables.